name: task_submission
description: A Flutter onboarding + alarm app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  timezone: ^0.9.2

  # Media
  video_player: ^2.8.2
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.3.1

  # Local Notifications
  flutter_local_notifications: ^17.1.2
  intl: ^0.19.0

  # Local Storage
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/audio/
    - assets/images/